name: Build AOCC

on:
  push:
    branches:
      - setup_ci
  # Schedule only
  #~ schedule:
    #~ - cron: '0 0 * * 0'

jobs:
  aocc:
    name: "Spack install Firedrake inside container using AOCC"
    #~ needs: docker_spack
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Build firedrake-spack-aocc
        uses: docker/build-push-action@v2
        with:
          push: false
          file: .github/workflows/docker/Dockerfile.aocc
          tags: firedrakeproject/firedrake-spack-aocc:latest
